services:
  sources:
    image: postgres:13
    container_name: sources
    restart: always
    environment:
      POSTGRES_DB: ${SRC_POSTGRES_DB}
      POSTGRES_USER: ${SRC_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SRC_POSTGRES_PASSWORD}
    ports:
      - "${SRC_POSTGRES_PORT}:5432"
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - source-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${SRC_POSTGRES_USER}"]
      interval: 10s
      retries: 5
    networks:
      - airflow-networks

networks:
  airflow-networks:
    external: true

volumes:
  source-volume:
    driver: local
    name: source-volume
